platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UICKeyChainStore', '~> 2.0.6'
pod 'Reachability', '~> 3.2'
pod 'RMAppStoreVersionCheck', '~> 1.0.1'
pod 'MJRefresh', '~> 2.0.1'
pod 'FMDB', '~> 2.5'
pod 'MJExtension', '~> 2.3.4'
pod 'DZNEmptyDataSet', '~> 1.5.2'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'SVWebViewController', '~> 1.0'
